version: '3'

services:
  app:
    container_name: app
    restart: unless-stopped
    build: .
    ports:
    - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: scrumProject
    image: mongo
    volumes:
    - ./data:/data/db
    ports:
    - "27017:27017"
